version: "3.8"

services:

  grafana:
    image: grafana/grafana:11.2.1
    container_name: grafana
    ports:
      - 3000:3000/tcp
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - loki_net

  loki:
    image: grafana/loki:3.2.0
    container_name: loki
    ports:
      - "3100:3100"
    command: 
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true
    volumes:
      - ./loki/config.yaml:/etc/loki/local-config.yaml
    networks:
      - loki_net

  fluent-bit:
    image: fluent/fluent-bit:3.1.9
    container_name: fluentbit
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224/udp"
    depends_on:
      - loki
    networks:
      - loki_net

networks:
  loki_net:
    name: loki_net